/**:
  ros__parameters:
    # -- System --
    sys_dt: 0.033     # sampling period.

    # options
    robust_options:
      use_switching_sigma: true
      use_deadzone: true
      use_dynamic_normalization: true
      tracking_tau: 0.1

      sigma_0: 0.01 # leakage sigma
      deadzone_threshold: 0.1 # radian for steering.
      delta0_norm_: 0.1 # normalization dynamics time-constant

    projection_options:
      smoother_eps: 0.05
      forgetting_factor: 0.99

    parameter_vars:
      a_upper_bound: 1.
      a_lower_bound: 0.01

      b_upper_bound: 1.
      b_lower_bound: 0.01

      param_normalized_upper_bound: 1. # normalized upper bound.


