/**:
  ros__parameters:
    # -- System --
    sys_dt: 0.033     # sampling period.

    # options
    robust_options:
      use_switching_sigma: false # if false, e-modification
      use_deadzone: true
      use_dynamic_normalization: true
      tracking_tau: 0.2
      am_stabilizing: 0.5 # the term to stabilize the amplitude of the signal xdot = (am - a)*x + b*u

      # FOR STABILIZATION
      sigma_0: 0.0001 # leakage sigma
      e_nu_0: 0.0001 # epsilon_nu for e-modification - to disable make these 0.

      # FOR ELIMINATING NOISE EFFECT
      deadzone_threshold: 0.02 # radian for steering.
      delta0_norm_: 0.1 # normalization dynamics time-constant

    projection_options:
      smoother_eps: 0.05
      forgetting_factor: 0.95

    parameter_vars:
      a_upper_bound: 1.     #~=tau_max
      a_lower_bound: 0.02   #~=tau_min

      b_upper_bound: 1.     #~=tau_max
      b_lower_bound: 0.02    # ~=tau_min

      param_normalized_upper_bound: 1. # normalized upper bound.


